version: '3.8'

services:
  # 前端服務
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

  # 後端服務
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION_IN}
    # depends_on:
    #   - db
    restart: always
    networks:
      - app-network

  # MySQL 資料庫服務
  # db:
  #   image: mysql:8.0
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=${DB_NAME}
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   networks:
  #     - app-network

# 設定持久資料卷
volumes:
  mysql-data:

# 定義網路
networks:
  app-network:
    driver: bridge
